version: '3.8'

# 可以使用 scale 动态扩容容器：docker-compose scale redis-replica=3

services:
  redis-primary:
    image: 'colovu/redis'
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=colovu
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/srv/data'

  redis-replica:
    image: 'colovu/redis'
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=colovu
      - REDIS_PASSWORD=colovu
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    depends_on:
      - redis-primary

# 定义本地数据卷，由系统管理，需要手动删除
volumes:
  redis_data:
    driver: local