version: '3.8'

# 伪集群方式配置时，各服务对外暴露的端口在映射到主机时，需要使用不同的端口，否则会导致端口冲突

# Docker-Compose 方式启动容器集群的 YAML 配置文件
# 当前配置仅保证可以启动容器；更多配置参数请参考镜像 README.md 文档中说明

services:
  redis:
    image: 'colovu/redis:5.0'
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=colovu
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/srv/data'

  redis-replica:
    image: 'colovu/redis:5.0'
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=colovu
      - REDIS_PASSWORD=colovu
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    depends_on:
      - redis

# 定义本地数据卷，由系统管理，需要手动删除
volumes:
  redis_data:
    driver: local